It's so cute!
urfu-2018/markup-task-4 pull request #10
Opened 2018-10-29 20:10 UTC by Nerzull3

2018-10-30 12:13 UTC, Nerzull3 commented
🍪

2018-10-30 12:14 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-25 18:02 UTC, spt30 requested changes
🍅Разметка сделана хорошо, молодец! По css есть немного замечаний:

2018-11-25 18:02 UTC, spt30 commented on index.css
> +    color: rgb(255, 255, 255);
Но ведь... можно написать `#fff`, так понятнее и короче

2018-11-25 18:02 UTC, spt30 commented on index.css
> +    width: 50px;
Грамотное и красивое решение, но кое-что забыл))
Ширина 50рх и высота тоже, а шрифт 40рх
Из-за этого при переворачивании скачет
Если ты хочешь выровнять текст по центру по вертикали, ставишь `line-height: 50px` (равный высоте блока) и будет все чудесно)

2018-11-25 18:02 UTC, spt30 commented on index.css
> +    color: rgb(255, 255, 255);
#fff, и далее тоже (если что, то три числа hex'а раскладываются в повторение, то есть будет #ffffff, то же самое)

2018-11-25 18:02 UTC, spt30 commented on index.css
> +    vertical-align: middle;
Это свойство ни на что не влияет, судя по всему

2018-11-25 18:02 UTC, spt30 commented on index.css
> +    max-width: 900px;
откуда цифры? Если ты хотел ограничить по экрану, то лучше написать что-то вроде 70vw

2018-11-25 18:02 UTC, spt30 commented on index.css
> +    box-shadow: 3px 2px 5px 2px rgb(0, 0, 0);
`#000`

2018-11-25 18:02 UTC, spt30 commented on index.css
> +    box-shadow: 3px 2px 5px 2px rgb(0, 0, 0);
Просто так напишу свой взгляд по дизайну: черные тени – плохо, можно что-то вроде `rgba(0, 0, 0, .15)` или `#00000026`, что ± то же самое

2018-11-25 18:02 UTC, spt30 commented on index.css
> +.name_of_cat:visited
из-за того, что ссылки у котиков одинаковые, visited проставляется сразу всем, если я перейду по одной ссылке

2018-11-25 18:02 UTC, spt30 commented on index.css
> +    margin-bottom: -5px;
ты что ли хацкер?))
это странная особенность работы img
если ты поставишь туда div с `background: url(...)`, все будет ок)

2018-11-25 19:04 UTC, Nerzull3 commented on index.css
> +.name_of_cat:visited
подразумевалось, что ссылочный текст будет всегда черным. Видимо, я не написал .name-of-cat:link { color: #000; }

2018-11-25 19:16 UTC, Nerzull3 commented on index.css
> +    margin-bottom: -5px;
У меня здесь возникала проблема с футером. background-картинке не хватало размера, чтобы покрыть весь футер по длине, поэтому она дублировалась, и получалось что-то типа этого:

![default](https://user-images.githubusercontent.com/32774760/48983432-85b80300-f110-11e8-85ae-fc70d6059de8.png)

2018-11-25 19:17 UTC, Nerzull3 commented on index.css
> +    margin-bottom: -5px;
А, всё, я понял, как исправить. Вопрос закрыт!

2018-11-25 20:01 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-26 17:48 UTC, spt30 commented on index.css
> +    box-shadow: 1px 1px 1px 1px #000;
возможно, я очень резко высказался в адрес `rgba()` функции
не всегда стоит использовать hex
в box-shadow и градиентах обычно пишется rgba()
ну это уже
1) субъективное мнение
2) объект договоренностей
3) придет с опытом

больше не буду за это ругать, извини)

2018-11-26 17:50 UTC, spt30 commented
🍏

2018-11-26 17:50 UTC, closed without merging