добавлено 10 котиков
urfu-2018/markup-task-4 pull request #100
Opened 2018-11-04 10:16 UTC by sHooKDT

2018-11-04 10:17 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-05 08:55 UTC, Xrias requested changes

2018-11-05 08:55 UTC, Xrias commented on index.css
> +    z-index: 2;
Не нужно

2018-11-05 08:55 UTC, Xrias commented on index.css
> +    overflow: visible;
Не нужно.

2018-11-05 08:55 UTC, Xrias commented
За что обделил последнего котика и не сделал для него картинку?((( Невидимая кнопка переключения.
<img width="1146" alt="2018-11-05 13 50 28" src="https://user-images.githubusercontent.com/27353659/47987616-cae4a880-e101-11e8-9619-30e59275d69d.png">

Не вижу длинного имени, хотя и стоит overflow, и обрезается не красиво, давай отступ еще добавим. Нет эффектов по наведению. Title у всех img надо проставить.

2018-11-05 18:05 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-05 18:16 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-05 18:22 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-05 19:06 UTC, closed without merging