initial commit
urfu-2018/markup-task-4 pull request #15
Opened 2018-10-30 08:31 UTC by KatySolo

2018-10-30 08:32 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-30 12:59 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-02 06:35 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-04 09:41 UTC, chrighter requested changes
🍅

2018-11-04 09:41 UTC, chrighter commented on index.css
> +    cursor: url('cats/black-paw.svg'), auto;
🔥

2018-11-04 09:41 UTC, chrighter commented on index.html
> +    <!-- <input type="radio" name="viewMode" value="grid" id="gridViewRadio" checked>
Давай уберем комментарии

2018-11-04 09:41 UTC, chrighter commented on index.html
> +    <div class="card">
Давай добавим семантику

2018-11-04 09:41 UTC, chrighter commented on index.html
> +
Лишняя строка

2018-11-04 09:41 UTC, chrighter commented on index.html
> +        <div class="name"><a href="" class="cat-name-link">Пугли</a></div>
Давай ссылки сделаем на `#`

2018-11-04 09:41 UTC, chrighter commented on index.html
> +        <img alt="navicon" src="navicon.png" class="navicon">
Иконки лучше делать `svg`-изображениями или при помощи `Iconfonts`

2018-11-04 09:41 UTC, chrighter commented on index.html
> +    <label for="switch" class="toggleContainer">
Давай не будем называть классы в `camelCase`

2018-11-04 09:41 UTC, chrighter commented on index.html
> +        <div class="name"><a href="" class="cat-name-link">
Можно `<a>` с новой строки

2018-11-04 09:41 UTC, chrighter commented on index.html
> +            Маруся-великая кошка-из-всех-кошек-и-кто-будет-спорить-тот-не-разбирается-кошках</a></div>
И `</div>` тоже с новой

2018-11-04 09:41 UTC, chrighter commented on index.html
> +        <img class="cat-image" src="cats/2.jpg" alt="Кошка Мишка">
![image](https://user-images.githubusercontent.com/22082557/47961970-f2227380-e036-11e8-8c0b-1d8a33c48f67.png)
Давай добавим отступ от края карточки

2018-11-04 09:41 UTC, chrighter commented on index.css
> +    border: 1px solid #808080;
Давай цвета единообразно именовать

2018-11-04 14:15 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-07 10:46 UTC, chrighter approved these changes
🍏

2018-11-07 10:46 UTC, chrighter commented on list-menu.svg
> +<?xml version="1.0" encoding="iso-8859-1"?>
Можно сжимать `svg`-изображения с помощью `svgo` https://www.npmjs.com/package/svgo

2018-11-07 10:46 UTC, closed without merging