Котики
urfu-2018/markup-task-4 pull request #24
Opened 2018-10-31 08:32 UTC by BlokhinaElizaveta

2018-10-31 08:33 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-08 13:47 UTC, nex2hex requested changes
🍅 
https://yadi.sk/i/TAj79ZjKbQ7OQA
при длинных текстах верстка ломается

остальные комментарии не критичны

2018-11-08 13:47 UTC, nex2hex commented on index.html
> +                <h3>Шоко</h3>
лучше ссылку внутри заголовка

2018-11-08 13:47 UTC, nex2hex commented on index.css
> +    transition: all .3s;
`transition: all` негативно влияет на производительность
лучше указывать конкретное свойство

2018-11-08 13:47 UTC, nex2hex commented on index.html
> +        <img src="img/img1.jpg" alt="котик">
ссылку на заголовок тоже логично было бы поставить

2018-11-08 16:12 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-08 16:13 UTC, BlokhinaElizaveta commented
:green_apple:  
поправила, теперь при длинных текстах выглядит так 
![image](https://user-images.githubusercontent.com/28544861/48211308-14035980-e39b-11e8-964d-272070341c81.png)

2018-11-08 16:16 UTC, closed without merging