Новиков Василий
urfu-2018/markup-task-4 pull request #3
Opened 2018-10-28 09:31 UTC by Toouren

2018-10-28 09:32 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-29 11:07 UTC, mokhov commented
Плохо что на текстовую ссылку можно навестись вне ссылки и она даже реагирует на это. Т.е если правее «Креветушка» навестись, то всё равно будет подчёркнуто

2018-10-29 11:10 UTC, mokhov requested changes
В целом неплохо, но не сделал часть про:
– Обрезать длинные имена котиков (=^ ◡ ^=)

2018-10-29 11:10 UTC, mokhov commented on index.html
> +            <div>
Вот как раз здесь вместо `div` надо `article`, а то что `article` надо сделать `section`

2018-10-29 11:10 UTC, mokhov commented on index.css
> +    margin: 5%;
Лучше явно задавать, а не в %

2018-10-29 11:32 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-13 12:56 UTC, mokhov commented
Ну ведь не сделал до сих пор « – Обрезать длинные имена котиков (=^ ◡ ^=)»

2018-11-13 13:03 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-13 13:06 UTC, Toouren commented
Я стили добавил для длинных имен, чтобы обрезались. Просто не было длинных имен в самой разметке. Сейчас добавил одно.

2018-11-19 05:41 UTC, closed without merging