Монин Константин
urfu-2018/markup-task-4 pull request #39
Opened 2018-10-31 16:13 UTC by Kuvadorian

2018-10-31 16:14 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-02 22:34 UTC, msmirnov requested changes
При отображении списком, фотки котиков получаются сжатыми на узком экране и растянутыми на широком экране. Это нужно исправить.

2018-11-02 22:34 UTC, msmirnov commented on index.css
> +    font-family: fantasy;
Такой шрифт есть далеко не на всех устройствах. Если хочется необычный шрифт, то его нужно подключить.

2018-11-03 10:39 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-03 10:40 UTC, Kuvadorian commented
🍏

2018-11-06 05:31 UTC, msmirnov commented on index.css
> +    font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
У меня в системе нет такого шрифта и он не отображается. Его здесь нужно либо убрать, либо сделать так, чтобы работало на всех устройствах (например, подключить внешний шрифт).

2018-11-06 05:34 UTC, msmirnov commented
🍅

2018-11-06 13:03 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-06 14:32 UTC, msmirnov approved these changes

2018-11-06 14:32 UTC, msmirnov commented
Так тоже нормально

2018-11-06 14:32 UTC, closed without merging