Иван Плаксин
urfu-2018/markup-task-4 pull request #49
Opened 2018-10-31 18:59 UTC by ZeroNetto

2018-10-31 19:00 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-31 19:05 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-04 09:07 UTC, chrighter requested changes
🍅

2018-11-04 09:07 UTC, chrighter commented on index.html
> +            <div class="card">
![image](https://user-images.githubusercontent.com/22082557/47961595-f1d2aa00-e02f-11e8-9e38-cb30f83b9d21.png)
Давай добавим отступы от края карточки

2018-11-04 09:07 UTC, chrighter commented on index.html
> +        </label>
Может быть перенести на 10 строчку?

2018-11-04 09:07 UTC, chrighter commented on index.css
> +    background-image: url(pictures/horizontal-view.jpg);
Иконки лучше делать с `svg`-изображениями или при помощи `Iconfonts`

2018-11-04 09:07 UTC, chrighter commented on index.css
> +    cursor: pointer;
👍

2018-11-04 09:07 UTC, chrighter commented on index.html
> +            <div class="card">
![image](https://user-images.githubusercontent.com/22082557/47961719-39f2cc00-e032-11e8-80dd-b97ee3766079.png)
Давай еще отступы между карточками добавим

2018-11-04 09:07 UTC, chrighter commented on index.css
> +.card a:hover
Давай еще как в задании реализуем эффекты при наведении на фото и категорию котика, сейчас у тебя реализованы на плитку и имя котика

2018-11-05 19:07 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-08 03:55 UTC, chrighter approved these changes
🍏

2018-11-08 03:55 UTC, chrighter commented on pictures/grid-view.svg
> +<svg class="cs-custom-icon" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="-1388 3226 30 30" style="enable-background:new -1388 3
Можно сжимать `svg`-изображения с помощью `svgo` https://www.npmjs.com/package/svgo

2018-11-08 03:55 UTC, closed without merging