Рыльских Алексей
urfu-2018/markup-task-4 pull request #58
Opened 2018-10-31 21:11 UTC by cfgi-lul

looks like it's done

2018-10-31 21:12 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-02 22:57 UTC, msmirnov requested changes
🍅

2018-11-02 22:57 UTC, msmirnov commented on index.html
> +        <fieldset class="cat-info">
`fieldset` не подходит здесь по смыслу, этот тег нужен для группировки элементов в форме, а это не форма

2018-11-02 22:57 UTC, msmirnov commented on index.html
> +            <img class="cat-photo" src="https://bit.ly/2yIg9m5" alt="cat_1" height="262">
У всех изображений одинаковый alt, а он нужен для отображения текста на месте незагруженного изображения. В этом атрибуте должен быть человекочитаемый текст.

2018-11-02 22:57 UTC, msmirnov commented on index.html
> +                <p class="diseases">Болезни: ---</p>
Вот эти пункты Возраст-Порода-Болезни лучше бы сделать в `<ul>`.

2018-11-02 22:57 UTC, msmirnov commented on index.html
> +            <img class="cat-photo" src="https://bit.ly/2yIg9m5" alt="cat_1" height="262">
Высоту картинок не нужно указывать в html-коде. Можно обойтись вообще без указания высоты.

2018-11-02 22:57 UTC, msmirnov commented on index.html
> +        <img id="checkbox-horizontal" class="img2" src="cb2.png" alt="">
img и img2 вообще непонятные названия классов

2018-11-03 16:10 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-06 05:34 UTC, msmirnov commented
![image](https://user-images.githubusercontent.com/2646531/48044756-6aac4000-e1af-11e8-86de-db04b6da89e6.png)
Текст не влазит, не получается прочитать
🍅

2019-01-12 05:01 UTC, closed without merging