Рожков Максим
urfu-2018/markup-task-4 pull request #64
Opened 2018-10-31 23:22 UTC by MaximRhz

Почему-то не работает добавление информации о коте, при нажатии на checkbox. Подскажи, что не так, пожалуйста)

2018-10-31 23:23 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-03 12:56 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-04 09:36 UTC, chrighter requested changes
🍅

2018-11-04 09:36 UTC, chrighter commented on index.css
> +    color: rgb(255, 0, 0);
Давай цвета единообразно именовать

2018-11-04 09:36 UTC, chrighter commented on index.css
> +.catImg
Давай не будем именовать классы в `camelCase`

2018-11-04 09:36 UTC, chrighter commented on index.css
> +    display: flex;
Хорошо, что ты знаешь про `flex`, но
![image](https://user-images.githubusercontent.com/22082557/47962174-82ae8300-e03a-11e8-86bd-e4d32d541d6d.png)

2018-11-04 09:36 UTC, chrighter commented on index.html
> +                <a  href="https://yandex.ru/search/?text=кот" class="catName">Барсик</a>
![image](https://user-images.githubusercontent.com/22082557/47962185-b2f62180-e03a-11e8-9ee2-f4880083044f.png)
![image](https://user-images.githubusercontent.com/22082557/47962318-15e8b800-e03d-11e8-919a-93d632f95c18.png)

Давай не только обрезать контент, который не влезает, но и заменять на многоточие, как на 2 скрине

2018-11-04 09:36 UTC, chrighter commented on index.html
> +
Лишняя строка

2018-11-04 09:36 UTC, chrighter commented on index.html
> +        </nav>
![image](https://user-images.githubusercontent.com/22082557/47962354-7b3ca900-e03d-11e8-9218-97ef6d98ac20.png)
Больше котиков

2018-11-04 09:36 UTC, chrighter commented on index.html
> +            <div class="cat">
Давай добавим семантику

2018-11-04 09:36 UTC, chrighter commented on index.html
> +                <p class="catDescription">Описание: Большой кот</p>
Давай выровняем текст по-левому краю как в макете
![image](https://user-images.githubusercontent.com/22082557/47962465-de7b0b00-e03e-11e8-8daf-11deec7ab44e.png)

2018-11-04 09:36 UTC, chrighter commented on index.html
> +                <a href="https://www.youtube.com/watch?v=fMnIpIMuBJIp" class="buy">Купить</a>
👍

2018-11-07 13:11 UTC, MaximRhz commented on index.html
> +            <div class="cat">
Исправил, но хотелось бы точнее, а то мог не все изменить)

2018-11-07 13:12 UTC, MaximRhz commented on index.html
> +                <p class="catDescription">Описание: Большой кот</p>
А мне кажется, что когда посредине, то лучше выглядит(

2018-11-07 14:32 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-07 14:33 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-07 17:03 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-08 04:34 UTC, chrighter requested changes
🍅

2018-11-08 04:34 UTC, chrighter commented on index.html
> +                    но я в этом не уверен</p>
Можно `</p>` с новой строки

2018-11-08 04:34 UTC, chrighter commented on index.html
> +                <span class="fick-text">М<span class="red-y">я</span>ндекс</span> Муррркет
Давай просто с `:first-letter`

2018-11-08 04:34 UTC, chrighter commented on index.css
> +    color: red;
Именование цветов

2018-11-08 04:34 UTC, chrighter commented on index.css
> +    box-shadow: inset 0 2px 3px rgba(0,0,0,.2);
Именование цветов

2018-11-08 04:34 UTC, chrighter commented on index.html
> +                <a  href="https://yandex.ru/search/?text=кот" class="cat-name">Хлебушек</a>
Можно было обернуть ссылку в какой-нибудь блочный элемент и на него навесить
```
white-space: nowrap;
overflow: hidden;
text-overflow: ellipsis;
```
чтобы текст обрезался и многоточием заменялся

2018-11-10 20:34 UTC, MaximRhz commented on index.html
> +                <span class="fick-text">М<span class="red-y">я</span>ндекс</span> Муррркет
"Я" не первая буква, а вторая

2018-11-10 20:45 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-12-05 10:49 UTC, chrighter approved these changes
🍏

2018-12-05 10:49 UTC, closed without merging