Решение задачи про котиков
urfu-2018/markup-task-4 pull request #7
Opened 2018-10-29 10:48 UTC by AIBarabanshchikova

2018-10-29 10:48 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-29 11:11 UTC, mokhov commented
<img width="276" alt="2018-10-29 16-11-15" src="https://user-images.githubusercontent.com/357689/47646289-4a6bf800-db95-11e8-9535-456ef77eb542.png">
Эффект прикольный сделала, но фиксировать высоту – bad idea

2018-10-29 11:13 UTC, mokhov requested changes
Очень хорошо. Чуть-чуть не хватает до шикарно 👍 
🍅

2018-10-29 11:13 UTC, mokhov commented on index.html
> +        <li class="cat-wrapper">
Тут лучше использовать article, а не список, т.к это не совсем список

2018-10-29 11:13 UTC, mokhov commented on index.html
> +                    <span>Возраст: 1,5 года</span>
Здесь можно использовал dl, dt, dd

2018-10-30 06:40 UTC, AIBarabanshchikova commented on index.html
> +                    <span>Возраст: 1,5 года</span>
Хорошо, на будущее учту.
Думала, что так делают только для определений.

2018-10-30 06:42 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-30 06:53 UTC, AIBarabanshchikova commented
Поправила высоту, теперь текст не вылезает за рамку.
![image](https://user-images.githubusercontent.com/38308325/47701051-65dd0e80-dc3a-11e8-902e-3ff5ab47d09b.png)

2018-10-30 06:54 UTC, AIBarabanshchikova commented
🍏

2018-11-19 05:43 UTC, mokhov commented
Всё отлично

2018-11-19 05:43 UTC, closed without merging