Гинзбург Елизавета
urfu-2018/markup-task-4 pull request #8
Opened 2018-10-29 16:12 UTC by LizaGin

2018-10-29 16:13 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-29 16:55 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-02 06:21 UTC, Xrias requested changes

2018-11-02 06:21 UTC, Xrias commented on index.css
> +header article p
Всем тегам нужно добавить класс в html и в css использовать именно класс.

2018-11-02 06:21 UTC, Xrias commented on index.html
> +    <section class="cat-information">
Мне кажется что контент подразделяется на article, а они уже на section, хотя конечно спорное утверждение. И давай добавим main.

2018-11-02 06:21 UTC, Xrias commented on index.html
> +                <img class="cat-img" src="./img/ДемиМурка.jpg" alt="Кошка Деми Мурка">
title всем img

2018-11-08 10:11 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-08 10:34 UTC, Xrias commented
Переключатель сломался.

2018-11-08 10:59 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-14 07:09 UTC, closed without merging