Раджабов Роман
urfu-2018/markup-task-4 pull request #81
Opened 2018-11-01 09:24 UTC by RadzhabovRoman

[Посмотреть решение](https://hruview.herokuapp.com/RadzhabovRoman/markup-task-4/master/index.html)

2018-11-01 09:25 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-25 19:52 UTC, spt30 requested changes
🍅 Привет! Есть замечание по общей раскладке:
При отображении плиткой остается много пустого места слева и справа
При отображении списком почему-то еще больше места и карточки не растягиваются:(

Пара замечаний по коду:

2018-11-25 19:52 UTC, spt30 commented on index.html
> +    <h1 class="titleCat">МОРЕ КОТОВ</h1>
Давай сделаем обычный текст, а регистр с помощью css

2018-11-25 19:52 UTC, spt30 commented on index.html
> +            <ul class="listCat">
можно выбрать другое, более понятное название класса, чем "список кота"

2018-11-25 19:52 UTC, spt30 commented on index.html
> +            <ul class="listCat">
И  желательно убрать маркеры-отбивки для элементов списка, уж больно глаза режет

2018-11-25 19:52 UTC, spt30 commented on index.css
> +    width: 71%;
откуда эти цифры?

2018-11-25 19:53 UTC, spt30 commented
Задачу решил за 3 часа до дедлайна, новый дедлайн по правкам до 3 декабря 04:00

2018-11-28 17:45 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-29 19:03 UTC, spt30 requested changes
🍅 Привет! Осталась одна маленькая проблема: при наведении на карточку, она увеличивается, все остальные начинают меня свои размеры и положение, давай это уберем и ок будет)

2018-11-29 20:12 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-12-04 14:53 UTC, spt30 commented
🍏

2018-12-04 14:53 UTC, closed without merging