Серов Егор
urfu-2018/markup-task-4 pull request #82
Opened 2018-11-01 09:34 UTC by Jueblack

Котики

2018-11-01 09:35 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-03 19:37 UTC, chrighter requested changes
🍅

2018-11-03 19:37 UTC, chrighter commented on index.html
> +<input type="radio" checked name="Change" value="button">Плитка<br>
![image](https://user-images.githubusercontent.com/22082557/47956434-3cb7d780-dfc6-11e8-8f17-4f87757cd0e6.png)
Давай сделаем переключатель как в задании

2018-11-03 19:37 UTC, chrighter commented on index.html
> +<p>
Зачем?

2018-11-03 19:37 UTC, chrighter commented on index.html
>  <body>
![image](https://user-images.githubusercontent.com/22082557/47956466-98826080-dfc6-11e8-87ad-fae22f7f2d55.png)
Где еще?)

2018-11-03 19:37 UTC, chrighter commented on index.html
> +        <a class="namelink" href="www.cat.ru" >Оченьдлинноеимякота</a>
Давай длинное имя будем не только заменять, но и добавлять многоточие в конце, например, как на скрине:
![image](https://user-images.githubusercontent.com/22082557/47956489-fa42ca80-dfc6-11e8-928a-1495feeabfb3.png)

2018-11-03 19:37 UTC, chrighter commented on index.html
> +
Зачем пустая строка?

2018-11-03 19:37 UTC, chrighter commented on index.html
> +        <div class="info">
Это точно отображается?

2018-11-03 19:37 UTC, chrighter commented on index.html
> +        <a class="namelink" href="www.cat.ru" >Снежок</a>
Лишний пробел перед `>`

2018-11-03 19:37 UTC, chrighter commented on index.html
> +
Давай уберем все лишние строки

2018-11-03 19:37 UTC, chrighter commented on index.html
> +</div>
Давай добавим семантику

2018-11-03 19:37 UTC, chrighter commented on index.html
> +         alt="lilcat">
Непонятный `alt`

2018-11-03 19:37 UTC, chrighter commented on index.html
> +<div class="block">
Давай более говорящее название сделаем

2018-11-03 19:37 UTC, chrighter commented on index.css
> +.block:hover
Давай как в задании реализуем эффекты при наведении не только на имя котика и плитку, но и на фото и категорию

2018-11-03 19:37 UTC, chrighter commented on index.html
> +    <h1 class="catname">
Лучше назвать класс `cat-name` и тд

2018-11-03 19:37 UTC, chrighter commented on index.html
> +<div class="block">
Давай добавим отступ от верхней границы блока, раз у тебя есть отступ от нижней границы
![image](https://user-images.githubusercontent.com/22082557/47956619-ec8e4480-dfc8-11e8-93b2-c5b506c2751d.png)

2018-11-03 19:37 UTC, chrighter commented on index.css
> +    font-variant: normal;
Что изменится, если убрать здесь стили `font-style` и `font-variant`?

2018-11-03 19:37 UTC, chrighter commented on index.css
> +    display: block;
`div` дефолтно блочный элемент, зачем ему задавать `display: block`?

2019-01-11 09:36 UTC, closed without merging