Cats
urfu-2018/markup-task-4 pull request #86
Opened 2018-11-01 10:21 UTC by VicClone

2018-11-01 10:21 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-03 17:59 UTC, dotokoto requested changes

2018-11-03 17:59 UTC, Dotokoto commented on index.html
> +        <input type="checkbox" name="displayOn" id="change-display" class="change-display">
В html и css не принято писать через camelCase.  `displayOn -> display-on`

2018-11-03 17:59 UTC, Dotokoto commented on index.html
> +                <img src="img-cats/1018925.jpg" alt="" class="photo-cat">
`alt` хорошо бы заполнить. Например, именами котов

2018-11-03 17:59 UTC, Dotokoto commented on index.html
> +                    <li class="blockOn">Порода: оцикет</li>
То же самое про имена классов - замени на `block-on`
Причем у тебя в некоторых местах один стиль, а в некоторых - другой. Хорошим тоном считается в проекте использовать единый стиль

2018-11-08 03:27 UTC, VicClone commented on index.html
> +        <input type="checkbox" name="displayOn" id="change-display" class="change-display">
Исправил

2018-11-08 03:27 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-08 03:27 UTC, VicClone commented on index.html
> +                <img src="img-cats/1018925.jpg" alt="" class="photo-cat">
Заполнил

2018-11-08 03:28 UTC, VicClone commented on index.html
> +                    <li class="blockOn">Порода: оцикет</li>
Убрал весь camelCase

2018-11-08 08:47 UTC, Dotokoto commented
Принято 👌

2018-11-08 08:47 UTC, closed without merging