Маклакова Елена
urfu-2018/markup-task-4 pull request #9
Opened 2018-10-29 19:27 UTC by elena-i-m98

[Посмотреть решение](https://hruview.herokuapp.com/elena-i-m98/markup-task-4/master/index.html)

2018-10-29 19:28 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-29 19:40 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-29 20:03 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-30 03:40 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-03 19:05 UTC, chrighter requested changes
🍅

2018-11-03 19:05 UTC, chrighter commented on index.css
> +.cat_block
Давай не будем именовать классы в `camel_case`

2018-11-03 19:05 UTC, chrighter commented on index.css
> +.short_info
Давай выровняем
![image](https://user-images.githubusercontent.com/22082557/47954534-d4a8c780-dfac-11e8-8c04-d4ccfc91d938.png)

2018-11-03 19:05 UTC, chrighter commented on index.html
> +                <p class="big_info">Спокойная, ласкова кошка.<br>
ласковая

2018-11-03 19:05 UTC, chrighter commented on index.html
> +                    Перкасно уживается с другими кошками<br>
Прекрасно

2018-11-03 19:05 UTC, chrighter commented on index.html
> +                    но очень нелюбит собак<br>
не любит

2018-11-03 19:05 UTC, chrighter commented on index.css
> +.cat_name
![image](https://user-images.githubusercontent.com/22082557/47954695-ec814b00-dfae-11e8-9488-37b6c5770a2e.png)
Давай выровняем

2018-11-03 19:05 UTC, chrighter commented on index.html
> +            <section class="cat_block">
![image](https://user-images.githubusercontent.com/22082557/47954935-767ee300-dfb2-11e8-95ae-6fe5b8aedf5d.png)
?

2018-11-03 19:05 UTC, chrighter commented on index.html
> +        <input type="radio" name="view" id="list_of_cats">
Почему один переключатель сделан с помощью `input` внутри `label`, а другой - с помощью `label for`? 
Давай сделаем единообразно

2018-11-03 19:05 UTC, chrighter commented on index.html
> +        <label><input type="radio" name="view" checked>Блоки-карточки котиков</label>
Давай стилизуем переключатель как в задании 
![image](https://user-images.githubusercontent.com/22082557/47955020-95ca4000-dfb3-11e8-81f8-23f40ebc6552.png)

2018-11-03 19:05 UTC, chrighter commented on index.html
> +                <a class="cat_name" href="#">Василёк</a> <br>
Лучше `<br>` на новую строку

2018-11-03 19:05 UTC, chrighter commented on index.html
> +                <a class="cat_name" href="#">Сиамка</a> <br>
Давай как у задании реализуем эффекты при наведении на имя котика, фото, категорию (у тебя сейчас только при наведении на плитку эффект)

2018-11-10 08:52 UTC, elena-i-m98 commented on index.html
> +            <section class="cat_block">
Не знаю, почему такое может быть...
![image](https://user-images.githubusercontent.com/43844991/48299511-6fdef700-e4ef-11e8-80f8-45d2531a4d29.png)
У меня отображается верно (обрезается имя и ставятся "...")
В коде для .cat-name есть свойства:
 ```
overflow: hidden;
 text-overflow: ellipsis;
 white-space: nowrap;
```
которые как раз и нужны для того, чтобы имя обрезалось, когда не входит в блок...

2018-11-10 08:55 UTC, elena-i-m98 commented on index.html
> +            <section class="cat_block">
проверила в другом браузере (Safari) 
тоже корректно отображается
![image](https://user-images.githubusercontent.com/43844991/48299566-54c0b700-e4f0-11e8-84ab-fc45bb6f6326.png)

2018-11-10 11:36 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-10 11:47 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-10 11:54 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-10 12:04 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-10 12:26 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-10 16:16 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-10 16:32 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-10 18:39 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-10 18:42 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-10 18:51 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-10 19:12 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-12-23 18:17 UTC, chrighter approved these changes
🍏

2018-12-23 18:17 UTC, closed without merging