Акишкина Вероника
urfu-2018/markup-task-4 pull request #96
Opened 2018-11-01 12:16 UTC by AirenLaird

К О Т И К И

2018-11-01 12:17 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-02 19:35 UTC, SemyonMakhaev requested changes
🍅 

Привет! Сейчас при наведении на изображение кота весь контент сдвигается вправо-вниз на несколько пикселей. Давай попробуем избавиться от этого поведения

2018-11-02 19:35 UTC, SemyonMakhaev commented on index.css
> +    border: 1px solid rgb(184, 183, 183);
Здесь не оправдано использование функции для вычисления цвета. Используй hex.
В других местах - аналогично

2018-11-02 19:35 UTC, SemyonMakhaev commented on index.css
> +[href]
Укажи явно, что в этом селекторе ты хочешь выбрать все ссылки. Лучше использовать селектор класса

2018-11-02 19:35 UTC, SemyonMakhaev commented on index.css
> +[type]:checked ~ main .cat figcaption .short
Можно ли уменьшить вложенность в селекторе?

2018-11-03 18:13 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-03 18:13 UTC, AirenLaird commented
🔔
Исправила эффект при наведении на изображение
1) Поняла, мне же не нужна прозрачность, поменяла на hex
2) Присвоила ссылками класс original и указала селектор класса;
3) Вложенность исправила (не знала, что можно указать любой вложенный класс потомка и будет работать)

2018-11-03 18:15 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-03 18:39 UTC, SemyonMakhaev requested changes
🍅 

Ещё одна небольшая оптимизация. Сейчас при первой загрузке страницы подгружаются все картинки, и контент скачет. Это можно предотвратить, указав ширину и высоту изображения в атрибутах [width](http://htmlbook.ru/html/img/width) и [height](http://htmlbook.ru/html/img/height). Это также позволит немного ускорить загрузку страницы, поскольку браузер не будет высчитывать размеры изображений.

Воспроизвести эффект можно, перезагрузив страницу с очисткой кэша `Ctrl+F5`

![screencast-2018-11-03-23-29-35](https://user-images.githubusercontent.com/18099714/47956115-80f4a900-dfc1-11e8-92bd-30d73ff68e6a.gif)

2018-11-03 18:39 UTC, SemyonMakhaev commented on index.css
> +[type]:checked ~ main .in_detail
Селекторы атрибута выглядят неочевидно, и их использование здесь неоправданно. К тому же они выбирают только один стилизуемый элемент - инпут. Можно указать это явно - добавить класс для элемента `input` и заменить селекторы атрибута на селекторы класса, тогда код станет более читаемым и понятным

2018-11-04 06:42 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-04 06:47 UTC, AirenLaird commented
🔔 как мне показывает хостинг, прописывание высоты не сильно помогло .-. даже если я у фигуры пропишу высоту (но в списке у меня подробное описание котиков разной высоты, поэтому статичную высоту фигуры, сделав, убрала)

2018-11-04 13:04 UTC, SemyonMakhaev commented
> 🔔 как мне показывает хостинг, прописывание высоты не сильно помогло .-. даже если я у фигуры пропишу высоту (но в списке у меня подробное описание котиков разной высоты, поэтому статичную высоту фигуры, сделав, убрала)

Да, если высоты у картинок разные, то такой поход не сработает. А ширину получится указать?

2018-11-04 13:40 UTC, AirenLaird commented
> > 🔔 как мне показывает хостинг, прописывание высоты не сильно помогло .-. даже если я у фигуры пропишу высоту (но в списке у меня подробное описание котиков разной высоты, поэтому статичную высоту фигуры, сделав, убрала)
> 
> Да, если высоты у картинок разные, то такой поход не сработает. А ширину получится указать?

Она же итак указана

2018-11-04 14:13 UTC, SemyonMakhaev commented
> Она же итак указана везде, я по ней делала

В атрибутах тега `img`? Не увидел

Фишка в том, чтобы в атрибуте передать размер изображения, тогда браузер не будет вычислять ширину и высоту, а сразу возьмёт переданные значения

http://htmlbook.ru/html/img/width

2018-11-04 14:24 UTC, AirenLaird commented
> > Она же итак указана везде, я по ней делала
> 
> В атрибутах тега `img`? Не увидел
> 
> Фишка в том, чтобы в атрибуте передать размер изображения, тогда браузер не будет вычислять ширину и высоту, а сразу возьмёт переданные значения
> 
> http://htmlbook.ru/html/img/width

Когда начинала еще, пробовала, линтинг запрещает указывать в атрибутах тега высоту и ширину:
Error: Bad value “300px” for attribute “width” on element “img”: Expected a digit but saw “p” instead.
From line 17, column 13; to line 18, column 41
Error: Bad value “225px” for attribute “height” on element “img”: Expected a digit but saw “p” instead.
From line 17, column 13; to line 18, column 41
There were errors.

2018-11-04 14:43 UTC, SemyonMakhaev commented
```
Error: Bad value “300px” for attribute “width” on element “img”: Expected a digit but saw “p” instead.
From line 17, column 13; to line 18, column 41
```

Это не запрет линтера. Это ошибка, в которой говорится, что значение атрибута должно быть числом

```html
<img width="300" height="400">
```

2018-11-04 14:52 UTC, AirenLaird commented
О боже, какой ужас, сейчас все сделаю

2018-11-04 15:00 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-04 19:57 UTC, SemyonMakhaev approved these changes
🍏 

Всё круто. Молодец, что разобралась с атрибутами!

2018-11-04 19:57 UTC, SemyonMakhaev commented on index.css
> +    width: 98%;
Сейчас изображение при наведении сильно разъезжается, потому размеры блока указаны в процентах. Это можно исправить, если зафиксировать их здесь в пикселях. У меня получились так:
```css
width: 294px;
height: 222px;
```

2018-11-04 19:58 UTC, closed without merging