add solution
urfu-2018/markup-task-4 pull request #97
Opened 2018-11-01 12:30 UTC by rundleman

2018-11-01 12:31 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-01 12:39 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-01 12:43 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-02 06:04 UTC, Xrias commented
1) Не меньше 10 котиков
2) Длинные имена котиков
3) Переключатель не работает
4) Нет эффектов при наведении

2018-11-02 06:15 UTC, Xrias requested changes

2018-11-02 06:15 UTC, Xrias commented on index.html
> +        <li class="card"><img src="img/asbis.jpg" alt="Абис">
title для img

2018-11-02 06:15 UTC, Xrias commented on index.html
> +        <li class="card"><img src="img/asbis.jpg" alt="Абис">
Ок, но почему все таки ul li а не article section? Переделвыать в этот раз не нужно, но в следующий давай с article

2018-11-07 10:19 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-07 11:08 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-07 11:11 UTC, rundleman commented on index.html
> +        <li class="card"><img src="img/asbis.jpg" alt="Абис">
Хорошо, я подумал, что это список котов

2018-11-08 09:25 UTC, Xrias commented
Апруфффф

2018-11-08 09:25 UTC, closed without merging