Ромасс Андрей
urfu-2018/markup-task-4 pull request #99
Opened 2018-11-02 19:24 UTC by Fylhtq42

[Посмотреть решение](https://hruview.herokuapp.com/Fylhtq42/markup-task-4/master/index.html)

2018-11-02 19:24 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-02 19:28 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-03 19:03 UTC, dotokoto requested changes
Хотелось бы еще, чтобы карточки в режиме списка не жались в левую часть экрана, а были по центру

2018-11-03 19:03 UTC, dotokoto commented on index.html
> +        <br>
`br` здесь лишний. Нужно выставить правильное свойство `display` у `label`, чтобы он не вставал в один ряд с карточками

2018-11-03 19:03 UTC, dotokoto commented on index.css
> +article.cat-card
Можно просто `.cat-card`

2018-11-03 19:03 UTC, Dotokoto commented on index.css
> +    content: 'Возраст: ';
Контентную часть не стоит выносить в `before/after`, они обычно используются для оформления. А это стоит оставить просто текстом в html

2018-11-03 19:03 UTC, Dotokoto commented on index.css
> +    -webkit-transition: all 1s ease-out;
Если используешь свойства с префиксами, всегда пиши последним и свойство без префикса. Так как под префиксом может быть тестовая или экспериментальная реализация, которая работает не совсем как надо. А без префикса - это уже стандарт, который будет работать по спецификации

2018-11-04 16:00 UTC, Fylhtq42 commented on index.css
> +    content: 'Возраст: ';
но это же фигово разве нет? Каждый раз прописывать возраст и другую штуку

2018-11-04 16:02 UTC, Fylhtq42 commented on index.css
> +    content: 'Возраст: ';
Но кажется я понял. Нельзя текст и любую осмысленную штуку выносить в бефор афтер. Так как смысловая часть все таки в html.

2018-11-04 16:09 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-06 07:55 UTC, Dotokoto commented on index.css
> +    content: 'Возраст: ';
Да, именно так )

2018-11-06 08:11 UTC, dotokoto commented on index.css
> +    margin-right: auto;
Можно записать в одно свойство: `margin: 0 auto` (или не 0, если у тебя сверху и снизу должен быть отступ)

2018-11-06 08:11 UTC, Dotokoto commented on index.css
> +    -o-transform: scale(1.1);
Не вижу свойств без префикса

2018-11-06 08:11 UTC, Dotokoto commented on index.css
> +    -webkit-transition: all 1s ease-out;
И здесь `transition` без префикса все еще не хватает

2018-11-06 09:27 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-06 09:33 UTC, Dotokoto commented
Принято 👌

2018-11-06 09:33 UTC, closed without merging